language: java

jdk:
 openjdk11
 
after_success:
  bash <(curl -s https://codecov.io/bash)

notifications:
    webhooks: https://travis-for-jira-prod.toolsplus.app/travis/notifications?token=13688d3f-a121-3217-9646-019f8dc06bfd
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
